name = "nintendo-switch-database-manager"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "nintendo-games-db"
database_id = "2bfcb37e-394d-4ce5-8201-140273523d6b"
migrations_dir = "drizzle"